[package]
name = "game-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dioxus.workspace = true
game-core = { path = "../game-core" }
protocol = { path = "../protocol" }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[features]
default = []
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
web = ["dioxus/web"]

[lints]
workspace = true
