[application]
name = "Rummy"
out_dir = "dist"
asset_dir = "assets"
sub_package = "game-server"

[web.app]
title = "Rummy"

[web.watcher]
watch_path = ["crates/game-ui", "crates/game-core", "crates/protocol", "assets"]

[web.resource]
style = ["/styles/main.css"]

[web.resource.dev]
style = []
script = []
