[package]
name = "test-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
game-core = { path = "../game-core" }
rand.workspace = true
rand_chacha.workspace = true
uuid.workspace = true

[lints]
workspace = true
